name: Build, Push and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04-arm

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Debug - List Files in Workspace
      run: ls -alh

    - name: Build and Push Docker Image
      run: |
        docker build -t cjarmas/guias-remision-v3 .
        docker push cjarmas/guias-remision-v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_PRIVATE_KEY }}
        script: |

          # Nos ubicamos en el directorio donde está el docker-compose.yml en el servidor
          cd compose

          # Si existe una imagen 'previous', la retagueamos a 'previous2'
          if docker image inspect cjarmas/guias-remision-v3:previous > /dev/null 2>&1; then
            docker tag cjarmas/guias-remision-v3:previous cjarmas/guias-remision-v3:previous2
          fi

          # Retagueamos la imagen 'latest' actual como 'previous'
          docker tag cjarmas/guias-remision-v3:latest cjarmas/guias-remision-v3:previous

          # Descargamos la nueva versión de la imagen 'latest' desde Docker Hub
          docker pull cjarmas/guias-remision-v3:latest

          # Si existe 'previous2', la eliminamos (limpieza de versiones antiguas)
          if docker image inspect cjarmas/guias-remision-v3:previous2 > /dev/null 2>&1; then
            docker image rm cjarmas/guias-remision-v3:previous2
          fi

          # Reiniciamos únicamente el contenedor del servicio mocab-web-services
          docker compose stop gplanet
          docker compose rm -f gplanet
          docker compose up -d gplanet
