name: Rollback to Previous Version

on:
  workflow_dispatch:  # Allows manual execution from GitHub Actions

jobs:
  rollback:
    runs-on: ubuntu-22.04-arm

    steps:
    - name: Connect via SSH and Perform Rollback
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_PRIVATE_KEY }}
        script: |
          # Navigate to the Docker Compose directory
          cd compose
          
          # Ensure the 'previous' image exists before proceeding
          if ! docker image inspect cjarmas/guias-remision-v3:previous > /dev/null 2>&1; then
            echo "No previous image available to rollback!" 
            exit 1
          fi
          
          # Tag latest as rollback (for safety)
          docker tag cjarmas/guias-remision-v3:latest cjarmas/guias-remision-v3:rollback
          
          # Tag previous as latest
          docker tag cjarmas/guias-remision-v3:previous cjarmas/guias-remision-v3:latest

          # Tag rollback as the new previous
          docker tag cjarmas/guias-remision-v3:rollback cjarmas/guias-remision-v3:previous

          # Remove the 'rollback' tag to maintain only 'latest' and 'previous'
          docker rmi cjarmas/guias-remision-v3:rollback || true
                    
          # Restart the container to use the rollbacked image
          docker compose stop gplanet
          docker compose rm -f gplanet
          docker compose up -d gplanet

          echo "Rollback completed successfully!"
